apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: todo-app-secrets
  namespace: todo-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: todo-app-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: __SECRETS_MANAGER_NAME__
